Add endpoints for third party developers to future API design
PermanentOrg/stela pull request #154
Opened 2024-12-12 18:42 UTC by liam-lloyd

We want to create a smooth process for third-party developers to integrate their apps with Permanent, or build their entire apps on top of Permanent. In pursuit of this, this commit adds several endpoints to our future API design, covering the creation of third-party developer accounts, the creation and management of third party applications in FusionAuth, and login via OAuth.

2024-12-12 20:00 UTC, slifty commented on packages/api/docs/future/models/application.yaml
> +  required: [id, claims]
I wonder if `claims` is supposed to generally be `scopes`

2024-12-12 20:01 UTC, slifty commented on packages/api/docs/future/paths/application.yaml
> +      Update an application's claims.
This lets someone update more than just the claims / scopes, right?  Might be worth updating the summary to be more generic.

2024-12-12 20:07 UTC, slifty requested changes
Looks great.

There's one thing to DRY up, then there's the `claims` vs `scopes` question that @meisekimiu raised

2024-12-12 20:07 UTC, slifty commented on packages/api/docs/future/paths/application.yaml
> +                    - record.create
This set of enum values exists in two places (and I think the list is coupled across both, so if one changes the other should too).  I don't think the enum value list can be reused, but the entire enum / type can become a schema definition.

Let's define the items in terms of a referenced schema type of `ApplicationScope` (or whatever name you think is best)

2024-12-12 23:46 UTC, liam-lloyd commented on packages/api/docs/future/models/application.yaml
> +  required: [id, claims]
Yeah, I changed the name and missed it here.

2024-12-13 22:55 UTC, meisekimiu reviewed
Should these also be `scopes` instead of `claims`?

2024-12-13 22:55 UTC, meisekimiu commented on packages/api/docs/future/paths/application.yaml
> +            required: [claims]
```suggestion
            required: [scopes]
```

2024-12-13 22:55 UTC, meisekimiu commented on packages/api/docs/future/paths/application.yaml
> +            required: [claims]
```suggestion
            required: [scopes]
```

2024-12-31 16:28 UTC, slifty approved these changes
Thanks for making those changes; this is lookin' clean and correct!

2025-01-06 22:31 UTC, merged